// <auto-generated />
using System;
using Diaryapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diaryapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Diaryapp.Models.DiaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "dfididjf",
                            Created_at = new DateTime(2024, 12, 8, 7, 50, 30, 278, DateTimeKind.Local).AddTicks(8773),
                            Title = "Went for a walk"
                        },
                        new
                        {
                            Id = 2,
                            Content = "I hate Jake",
                            Created_at = new DateTime(2024, 12, 8, 7, 50, 30, 278, DateTimeKind.Local).AddTicks(9682),
                            Title = "I need to lock-in"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
